add `no-reactive-functions` rule
ota-meshi/eslint-plugin-svelte pull request #206
Opened 2022-07-31 05:19 UTC by tivac

## :book: Rule Details

This rule reports whenever a function is defined in a reactive statement. This isn't necessary, as each time the function is executed it'll already have access to the latest values necessary. Redefining the function in the reactive statement is just a waste of CPU cycles.

```svelte
<script>
  /* eslint svelte/no-reactive-functions: "error" */

  /* ✓ GOOD */
  const arrowFn = () => { /* ... */ }
  const func = function() { /* ... */ }
  
  /* ✗ BAD */
  $: arrowFn = () => { /* ... */ }
  $: func = function() { /* ... */ }
</script>
```

2022-08-02 00:01 UTC, ota-meshi requested changes

2022-08-02 00:01 UTC, ota-meshi commented on src/rules/no-reactive-functions.ts
> +                )
If there is no space after the colon (`:`), I think we should change it to:

```suggestion
                // Replace the entire reactive label with "const"
                return fixer.replaceTextRange(
                  [parent.range[0], node.parent.parent.range[0],
                  "const ",
                )
```

Test case
```js
/* prettier-ignore */
$:bar = foo.bar
```

2022-08-03 05:33 UTC, ota-meshi commented on docs/rules/no-reactive-functions.md
> +description: ""
Could you run `yarn update` and update the header?

2022-08-03 06:32 UTC, ota-meshi approved these changes
LGTM! Thank you very much!

2022-08-03 11:27 UTC, JounQin approved these changes

2022-08-03 11:50 UTC, merged