Added the `require-event-dispatcher-types` rule
ota-meshi/eslint-plugin-svelte pull request #354
Opened 2023-02-01 20:52 UTC by marekdedic

Let's start with a few tests...

2023-02-03 09:04 UTC, ota-meshi requested changes
Thank you for this PR! I made some comments.

2023-02-03 09:04 UTC, ota-meshi commented on src/rules/require-event-dispatcher-types.ts
> +      Program() {
I think we need to check if `lang="ts"` is specified before we check it.

```suggestion
    let isTs = false
    return {
      SvelteScriptElement(node) {
        const lang = getLangValue(node)?.toLowerCase()
        if (lang === "ts" || lang === "typescript") {
          isTs = true
        }
      },
      "Program:exit"() {
        if (isTs) return
```

2023-02-03 09:04 UTC, ota-meshi commented on tests/fixtures/rules/require-event-dispatcher-types/invalid/no-types01-input.svelte
> +<script lang="ts">
Could you add another test case without `lang="ts"`?

2023-02-03 17:21 UTC, marekdedic commented
Thanks for the review :) It's a good catch that the rule should probably ignore non-ts code outright.

2023-02-04 00:01 UTC, ota-meshi approved these changes
LGTM! Thank you!

2023-02-04 00:02 UTC, merged